spring:
  application:
    name: cost-request-service

  r2dbc:
    url: ${DB_URL:r2dbc:postgresql://localhost:5432/priceflow_cost_request}
    username: ${DB_USERNAME:priceflow}
    password: ${DB_PASSWORD:priceflow}

  flyway:
    enabled: true
    url: ${FLYWAY_DB_URL:jdbc:postgresql://localhost:5432/priceflow_cost_request}
    user: ${DB_USERNAME:priceflow}
    password: ${DB_PASSWORD:priceflow}
    locations: classpath:db/migration
    baseline-on-migrate: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.apicurio.registry.serde.avro.AvroKafkaSerializer

      properties:
        apicurio.registry.url: ${SCHEMA_REGISTRY_URL:http://localhost:8085/apis/registry/v3}
        apicurio.registry.auto-register: true
priceflow:
  kafka:
    schema-registry-url: ${SCHEMA_REGISTRY_URL:http://localhost:8085/apis/ccompat/v7}

management:
  endpoints:
    web:
      exposure:
        include: health,info