spring:
  application:
    name: cost-request-service

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/priceflow_cost_request
    username: priceflow
    password: priceflow

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.apicurio.registry.serde.avro.AvroKafkaSerializer

      properties:
        apicurio.registry.url: http://localhost:8085/apis/registry/v3
        apicurio.registry.auto-register: true

management:
  endpoints:
    web:
      exposure:
        include: health,info