apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricing-service
  namespace: priceflow
spec:
  replicas: 1

  selector:
    matchLabels:
      app: pricing-service

  template:
    metadata:
      labels:
        app: pricing-service

    spec:
      containers:
        - name: pricing-service
          image: ghcr.io/tejesh649/priceflow-pricing-service@sha256:7f58355abe29d0f40f384dc468a5a96ca6589fff67cc4f485f2a12f75c8f64a5

          ports:
            - name: http
              containerPort: 8081

          env:
            - name: DB_URL
              value: r2dbc:postgresql://postgres:5432/priceflow_pricing

            - name: FLYWAY_DB_URL
              value: jdbc:postgresql://postgres:5432/priceflow_pricing

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:29092

            - name: SCHEMA_REGISTRY_URL
              value: http://schema-registry:8080/apis/ccompat/v7

---
apiVersion: v1
kind: Service
metadata:
  name: pricing-service
  namespace: priceflow
spec:
  selector:
    app: pricing-service

  ports:
    - name: http
      port: 8081
      targetPort: 8081

  type: ClusterIP
