spring:
  application:
    name: notification-service

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/priceflow_notification
    username: priceflow
    password: priceflow

  logging:
    level:
      org.springframework.r2dbc.core: DEBUG

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info

priceflow:
  notification:
    test-recipient: ${NOTIFICATION_TEST_RECIPIENT}