spring:
  application:
    name: notification-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info

priceflow:
  notification:
    test-recipient: ${NOTIFICATION_TEST_RECIPIENT}